/**
 * Clones every published `unit` (Corp A) document into a `unitCorpB` document.
 *
 * Per clone: `_id` gets the `corpB-` prefix, `uniqueId` gets the `-b` suffix,
 * `sold` is left unset and `price` is 0. Floor, image and PDF references are kept.
 * Uses createIfNotExists, so re-running never overwrites clones edited since.
 *
 * Dry run by default. Run from studio-nosto:
 *   npx sanity exec scripts/cloneUnitsToCorpB.ts --with-user-token
 * Write for real:
 *   CLONE_COMMIT=1 npx sanity exec scripts/cloneUnitsToCorpB.ts --with-user-token
 */
import {getCliClient} from 'sanity/cli'

const SOURCE_TYPE = 'unit'
const TARGET_TYPE = 'unitCorpB'
const ID_PREFIX = 'corpB-'
const UNIQUE_ID_SUFFIX = '-b'
/** System fields are regenerated by Sanity; `sold` is intentionally left unset on clones. */
const DROPPED_FIELDS: readonly string[] = [
  '_id',
  '_type',
  '_rev',
  '_createdAt',
  '_updatedAt',
  'sold',
]

interface UnitDoc extends Record<string, unknown> {
  _id: string
  _type: string
  uniqueId?: string
}

interface CorpBDoc extends Record<string, unknown> {
  _id: string
  _type: typeof TARGET_TYPE
  uniqueId?: string
  price: 0
}

const client = getCliClient({apiVersion: '2025-02-19'})
const commit = process.env.CLONE_COMMIT === '1'

function toCorpB(doc: UnitDoc): CorpBDoc {
  const kept: Record<string, unknown> = Object.fromEntries(
    Object.entries(doc).filter(([key]) => !DROPPED_FIELDS.includes(key)),
  )
  return {
    ...kept,
    _id: `${ID_PREFIX}${doc._id}`,
    _type: TARGET_TYPE,
    ...(doc.uniqueId ? {uniqueId: `${doc.uniqueId}${UNIQUE_ID_SUFFIX}`} : {}),
    price: 0,
  }
}

async function main() {
  const units = await client.fetch<UnitDoc[]>(
    `*[_type == $type && !(_id in path("drafts.**"))] | order(uniqueId asc)`,
    {type: SOURCE_TYPE},
  )
  const existingIds = new Set(
    await client.fetch<string[]>(`*[_type == $type]._id`, {type: TARGET_TYPE}),
  )
  const clones = units.map(toCorpB)
  const toCreate = clones.filter((c) => !existingIds.has(c._id))

  console.log(
    `Found ${units.length} published "${SOURCE_TYPE}" docs; ` +
      `${existingIds.size} "${TARGET_TYPE}" docs already exist; ${toCreate.length} to create.\n`,
  )
  for (const c of clones) {
    const status = existingIds.has(c._id) ? 'skip (exists)' : 'create'
    console.log(
      `${status.padEnd(14)} ${c._id.padEnd(48)} uniqueId=${String(c.uniqueId).padEnd(10)} ` +
        `name=${String(c.name).padEnd(14)} price=${c.price} sold=${'sold' in c ? 'SET' : 'unset'}`,
    )
  }

  if (!commit) {
    console.log(
      '\nDry run only. Nothing written. Re-run with CLONE_COMMIT=1 to create the documents.',
    )
    return
  }
  if (toCreate.length === 0) {
    console.log('\nNothing to create.')
    return
  }

  const tx = toCreate.reduce((t, c) => t.createIfNotExists(c), client.transaction())
  const result = await tx.commit()
  console.log(
    `\nCommitted transaction ${result.transactionId} with ${result.results.length} mutations.`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
